# device 
device: 'cuda:0'

# training params
#epochs: 10 # number of epochs
#batch_size: 1
#lr: 0.0001 # learning rate
epochs: 255 # number of epochs
batch_size: 24
lr: 0.01 # learning rate
gamma: 0.1 # learning drop
lr_steps: [75, 180]
# lr 0.01, 0.001, 0.0001
# 1% data epochs: 7500, 18000, 25500
# 5% data epochs: 1500, 3600, 5100
# 10% data epochs: [1200, 2200, 3300], [750, 1800, 2550]
# 100% data epochs: 250, 600, 850
# 100% data 30% epochs: 75, 180, 255

# dataset
crop_size: 256
thresh: 0.76

# dirs
checkpoints_dir: './checkpoints/'
# test
test: False # whether run test
load_checkpoint: './checkpoints/model_last/1data_25500epoch/naive_baseline_best.pth' # if test is True, load the checkpoint
# 1% iter0
# ./checkpoints/model_last/1data_25500epoch/naive_baseline_best.pth
# 1% iter0 ta+tta
# ./checkpoints/model_last/1data_25500epoch/exp1.2_best_thr0_ta_tta_iter/iter0/naive_baseline_best.pth
# 1% iter1
#'./checkpoints/model_last/1data_25500epoch/exp1_best_thr0_iter/best_thr0.76and0_iter1/naive_baseline_best.pth'
# 5% iter0
#./checkpoints/model_last/5data_5100epoch/naive_baseline_best.pth
# 5% iter0 ta+tta
# ./checkpoints/model_last/5data_5100epoch/exp5.2_best_thr0_ta_tta_iter/iter0/naive_baseline_best.pth
# 5% iter1
# ./checkpoints/model_last/5data_5100epoch/exp5_best_thr0_iter/best_thr0.76and0_iter1/naive_baseline_best.pth

# resume
resume: False # whether resume

# training data
data_argumentation: True # whether training dat argumentation

# test setting
thr0: False # whether use threshold = 0 for prediction
tta: True # whether test-time argumentation
tta_thr: 0.2 # threshold for prediction with tta
no_tta_thr: 0 # threshold for prediction without tta

# skeleton threshold
skeleton_thr: 0.2
skeleton_ig_line: 5

# docker 
docker_sub_dir: segmentation_based_baselines/naive_baseline
docker_container_name: topo_naive
docker_port_number: 5001