# device 
device: 'cuda:0'

# training params
#epochs: 10 # number of epochs
#batch_size: 1
#lr: 0.0001 # learning rate
epochs: 600 # number of epochs
batch_size: 24
lr: 0.01 # learning rate

# dataset
crop_size: 256
thresh: 0.76

# dirs
checkpoints_dir: './checkpoints/'
# test
test: False # whether run test
load_checkpoint: './checkpoints/naive_baseline_20.pth' # if test is True, load the checkpoint
# resume
resume: False # whether resume

# docker 
docker_sub_dir: segmentation_based_baselines/naive_baseline
docker_container_name: topo_naive
docker_port_number: 5001